### ISSUE TITLE
Support Flash Storage in native Desktop Environment

### ISSUE THREAD

**Issue by prathje** [CovidBraceletPrj/CovidBracelet#16]
We should add the ability to store records etc. also in the Desktop Environment to allow for testing.

**Comment by prathje** [comment]
See https://docs.zephyrproject.org/latest/boards/posix/native_posix/doc/index.html#host-based-flash-access and https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_FLASH_SIMULATOR.html#cmdoption-arg-CONFIG_FLASH_SIMULATOR

**Comment by H1ghBre4k3r** [comment]
Can't we close this issue due to #22 being merged?
