### ISSUE TITLE
platformio run cannot build "desktop" version

### ISSUE THREAD

**Issue by pinkit-cwa** [CovidBraceletPrj/CovidBracelet#4]
end of out is:

> Processing desktop (platform: native)
> --------------------------------------------------------------------------------------------------------------------------------------------------------
> Verbose mode can be enabled via `-v, --verbose` option
> LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
> LDF Modes: Finder ~ chain, Compatibility ~ off
> Found 2 compatible libraries
> Scanning dependencies...
> Dependency Graph
> |-- <mbedtls> 2.23.0
> Error: Nothing to build. Please put your source code files to '/home/a/bracelets/CovidBracelet/src' folder
> ============================================================== [FAILED] Took 0.80 seconds ==============================================================
> 
> Environment    Status    Duration
> -------------  --------  ------------
> nrf52840_dk    SUCCESS   00:00:05.220
> desktop        FAILED    00:00:00.797
> ======================================================== 1 failed, 1 succeeded in 00:00:06.017 ========================================================

**Comment by olafland** [comment]
@prathje, could you have a look? We need the Desktop mode for testing the Mbed Stuff, correct?

**Comment by prathje** [comment]
Yes, the desktop mode is currently only used for testing. However as all src files are ignored, there is indeed nothing to built. This is fixed with b99f373 👍
